title: Bigmood Sesshins sandbox
description: Set notes & artifacts from voice sesshins on NiftyRecordsNFT community discord server
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
