title: Bigmood Sesshins sandbox
description: Set notes & artifacts for voice sesshins on NiftyRecordsNFT discord server
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
